package com.ExceptionHandling;

public class Ex_09_ExceptionHandling {

	public static void main(String[] args) {
		try{
			System.out.println(10/0);
		}
		catch(ArithmeticException e){
			
		}
		
//		catch(ArithmeticException e){
//			Arithmetic Exception already been caught
//		}
//		
	}
}
